import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'
import Header from '@/components/layouts/Header'
import LeftAside from '@/components/layouts/LeftAside'
import RightAside from '@/components/layouts/RightAside'
import Footer from '@/components/layouts/Footer'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({      //  Function Start
  children,
}: {
  children: React.ReactNode
}) {

  //    Function Return Statement
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className='container p-0 a_tbdr'>
         <Header />
          <main className='h-100'>
            <div className='row h-100 m-0'>
              <LeftAside />
        {children}
        <RightAside />
            </div>
          </main>
          <Footer />
      </div>
        
        </body>
    </html>
  )
}       //    Function End
